# Example .airstack.yml file

name: airstack-blog
user: airstack
container:
  type: airstack/node
  version: ^0.10

source: ./
scripts:
  start:
    pre: git fetch
    run: npm start
    post: npm clean
  stop: ./stop.sh
  restart: ./stop.sh && npm start

watch:
  - path: /content
    script: restart

services:
  - sshd
  - rsyslog
  - newrelic


ENV:
  SOME_APP_ENV_STUFF: asdfasdfasdf


components:
  - name: db
    container:
      type: airstack/mysql
      version: ^5.6
    ENV:
      ENGINE_TYPE: innodb
  - name: worker
    user: worker
    source: ./worker
    scripts:
      start: npm run --worker

